### ISSUE TITLE
After updating from v2.2.0 to v2.2.4 get javascript error on load

### ISSUE THREAD

**Issue by JamesReate** [arsmn/fiber-swagger#18] opened 2022-02-22 17:31 UTC
After updating our project to use 2.2.4 eg:
`go get: upgraded github.com/arsmn/fiber-swagger/v2 v2.2.0 => v2.24.0`

the swagger WebApp started giving a javascript error. I also noticed it did not download the `.json` file that it normally does, which makes sense with the error as it fails on the `downloadSpec()` func.

<img width="965" alt="image" src="https://user-images.githubusercontent.com/2886324/155186218-de19ccad-8b57-4b85-bd8a-988933ddddb9.png">

**Comment by fujiawei-dev** [comment] 2022-02-23 07:56
I had the same problem.

**Comment by DoubleDi** [comment] 2022-03-09 23:06
2.20.0 does not have this problem

**Comment by timo-klarshift** [comment] 2022-03-11 06:58
I am also having this issue

**Comment by alhamsya** [comment] 2022-03-20 06:01
me too

**Comment by arsmn** [comment] 2022-03-30 10:57
I'm unable to reproduce this error.
Can you share more details?

**Comment by nedpuganti9** [comment] 2022-04-01 04:47
its when you do custom config

**Comment by arsmn** [comment] 2022-04-02 11:59
The problem was new configuration and default values.
The necessary plugins and presets were not included when custom config was used.
It's fixed in new version v2.31.1.

**Closed by arsmn** 2022-04-02 11:59 UTC
